version: '3.8'

services:
  postgres:
    image: postgres
    container_name: licoflix001db
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "licoflix001db"
    ports:
      - "5432:5432"
    volumes:
      - ./init/database-scripts.sql:/docker-entrypoint-initdb.d/database-scripts.sql
    restart: unless-stopped